// Code generated by xyz; DO NOT EDIT.
// This file will be ignored for default config since it is generated. Since
// it's ignored it also doesn't have a golden file.
package pkg

func Fn() {

	if true {

		_ = 1
	}
	if false {
		_ = 2

	}
}
