// Code generated by xyz; DO NOT EDIT.
package pkg

func Fn() { // want "block should not start with a whitespace"

	if true { // want "block should not start with a whitespace"

		_ = 1
	}
	if false { // want "if statements should only be cuddled with assignments"
		_ = 2

	} // want "block should not end with a whitespace"
}
